import {
  Activity,
  AlertTriangle,
  Archive,
  BadgeEuro,
  BarChart3,
  Bell,
  Boxes,
  CalendarDays,
  ClipboardCheck,
  Clock3,
  Code2,
  FileArchive,
  FileDown,
  FileScan,
  FileSpreadsheet,
  History,
  PackageCheck,
  Printer,
  ReceiptText,
  Settings,
  ShieldCheck,
  Sparkles,
  Tags,
  Truck,
  UploadCloud,
  Users,
  Utensils,
} from "lucide-react";

export const modules = [
  {
    href: "/invoices",
    title: "OCR IA factures fournisseurs",
    description: "Upload, extraction IA, controle humain, rapprochement fournisseur et archivage.",
    status: "Base upload API prete",
    icon: FileScan,
  },
  {
    href: "/suppliers",
    title: "Gestion fournisseurs",
    description: "Contacts, delais, conditions, catalogue, historique d'achat et performance.",
    status: "API CRUD initiale",
    icon: Truck,
  },
  {
    href: "/stock",
    title: "Stocks intelligents",
    description: "Niveaux temps reel, seuils, mouvements, valorisation et alertes de rupture.",
    status: "Modele de donnees pret",
    icon: Boxes,
  },
  {
    href: "/inventory",
    title: "Inventaires",
    description: "Comptages mobiles, ecarts, validations manager et ajustements auditables.",
    status: "A implementer",
    icon: ClipboardCheck,
  },
  {
    href: "/recipes",
    title: "Fiches techniques",
    description: "Ingredients, rendements, cout portion, prix de vente et allergenes consolides.",
    status: "Modele de donnees pret",
    icon: Utensils,
  },
  {
    href: "/sub-recipes",
    title: "Sous-recettes",
    description: "Bases, sauces, preparations labo, rendements par lot et couts imbriques.",
    status: "Modele de donnees pret",
    icon: Archive,
  },
  {
    href: "/costs",
    title: "Couts matieres",
    description: "Calculs automatiques depuis achats, fiches, pertes et inventaires.",
    status: "A implementer",
    icon: BadgeEuro,
  },
  {
    href: "/margins",
    title: "Marges",
    description: "Pilotage marge brute, marge nette estimee, mix produit et derives.",
    status: "Dashboard initial",
    icon: BarChart3,
  },
  {
    href: "/allergens",
    title: "Allergenes",
    description: "Matrice allergenes ingredients, recettes, etiquettes et exports salle.",
    status: "Champ stock pret",
    icon: AlertTriangle,
  },
  {
    href: "/haccp",
    title: "HACCP / PMS",
    description: "Plan de maitrise sanitaire, controles, preuves, actions correctives.",
    status: "API temperatures prete",
    icon: ShieldCheck,
  },
  {
    href: "/temperatures",
    title: "Releves temperatures",
    description: "Saisie mobile, conformite, alertes froid/chaud et historique exportable.",
    status: "API CRUD initiale",
    icon: Activity,
  },
  {
    href: "/labels",
    title: "Etiquettes",
    description: "DLC, lots, allergenes, QR codes et impression cuisine.",
    status: "A implementer",
    icon: Tags,
  },
  {
    href: "/production",
    title: "Production labo",
    description: "Ordres de production, besoins, lots, rendements et tracabilite.",
    status: "Navigation prete",
    icon: PackageCheck,
  },
  {
    href: "/planning",
    title: "Planning employes",
    description: "Equipe, postes, absences, cout main d'oeuvre et publication mobile.",
    status: "Navigation prete",
    icon: CalendarDays,
  },
  {
    href: "/time-clock",
    title: "Badgeuse employes",
    description: "Pointage, pauses, validation manager et export paie.",
    status: "Modele de donnees pret",
    icon: Clock3,
  },
  {
    href: "/analytics",
    title: "Analytics",
    description: "Ventes, achats, pertes, productivite, food cost et previsions.",
    status: "Dashboard initial",
    icon: BarChart3,
  },
  {
    href: "/ai",
    title: "IA predictive",
    description: "Prevision de demande, ruptures, achats recommandes et anomalies.",
    status: "Navigation prete",
    icon: Sparkles,
  },
  {
    href: "/orders",
    title: "Commandes fournisseurs",
    description: "Suggestions, bons de commande, statuts, reception et ecarts facture.",
    status: "Navigation prete",
    icon: ReceiptText,
  },
  {
    href: "/ladition",
    title: "Synchronisation caisse L'Addition",
    description: "Import ventes, mix produits, rapprochement recettes et donnees analytics.",
    status: "Connecteur a implementer",
    icon: FileSpreadsheet,
  },
  {
    href: "/api-console",
    title: "API REST complete",
    description: "Documentation, tokens, webhooks, journaux API et integration partenaires.",
    status: "FastAPI OpenAPI actif",
    icon: Code2,
  },
  {
    href: "/notifications",
    title: "Notifications temps reel",
    description: "WebSocket, alertes stock, HACCP, imports OCR et actions manager.",
    status: "WebSocket initial",
    icon: Bell,
  },
  {
    href: "/uploads",
    title: "Upload drag and drop",
    description: "Depot factures, photos, pieces jointes et analyse asynchrone.",
    status: "Endpoint facture pret",
    icon: UploadCloud,
  },
  {
    href: "/reports",
    title: "PDF et Excel",
    description: "Exports compta, inventaire, HACCP, etiquettes, fiches techniques.",
    status: "A implementer",
    icon: FileDown,
  },
  {
    href: "/history",
    title: "Historique complet",
    description: "Timeline achats, stocks, recettes, employes, imports et validations.",
    status: "Audit model pret",
    icon: History,
  },
  {
    href: "/audit",
    title: "Audit logs",
    description: "Journal inviolable des actions critiques, roles et changements.",
    status: "API ecriture partielle",
    icon: FileArchive,
  },
  {
    href: "/settings",
    title: "Parametres entreprise",
    description: "Societe, restaurants, utilisateurs, roles, securite et integrations.",
    status: "Modele de donnees pret",
    icon: Settings,
  },
  {
    href: "/team",
    title: "Multi-utilisateurs",
    description: "Invitations, roles, permissions par restaurant et audit d'acces.",
    status: "RBAC initial",
    icon: Users,
  },
  {
    href: "/print",
    title: "Impression cuisine",
    description: "Etiquettes, fiches, ordres de production et exports operationnels.",
    status: "A implementer",
    icon: Printer,
  },
];

export type ModuleDefinition = (typeof modules)[number];

export function getModuleByHref(href: string) {
  return modules.find((module) => module.href === href);
}
