import {
  Activity,
  AlertTriangle,
  Archive,
  BadgeEuro,
  BarChart3,
  Bell,
  Boxes,
  CalendarDays,
  ClipboardCheck,
  Clock3,
  Code2,
  FileArchive,
  FileDown,
  FileScan,
  FileSpreadsheet,
  History,
  PackageCheck,
  Printer,
  ReceiptText,
  Settings,
  ShieldCheck,
  Tags,
  Truck,
  UploadCloud,
  Users,
  Utensils,
} from "lucide-react";

export const modules = [
  {
    href: "/invoices",
    title: "OCR IA factures fournisseurs",
    description: "Import, extraction IA, contrôle humain, rapprochement fournisseur et archivage.",
    status: "Base import API prête",
    icon: FileScan,
  },
  {
    href: "/suppliers",
    title: "Gestion fournisseurs",
    description: "Contacts, délais, conditions, catalogue, historique d'achat et performance.",
    status: "API CRUD initiale",
    icon: Truck,
  },
  {
    href: "/stock",
    title: "Stocks intelligents",
    description: "Niveaux temps réel, seuils, mouvements, valorisation et alertes de rupture.",
    status: "Modèle de données prêt",
    icon: Boxes,
  },
  {
    href: "/inventory",
    title: "Inventaires",
    description: "Comptages mobiles, écarts, validations manager et ajustements auditables.",
    status: "À implémenter",
    icon: ClipboardCheck,
  },
  {
    href: "/recipes",
    title: "Fiches techniques",
    description: "Ingrédients, rendements, coût portion, prix de vente et allergènes consolidés.",
    status: "Modèle de données prêt",
    icon: Utensils,
  },
  {
    href: "/sub-recipes",
    title: "Sous-recettes",
    description: "Bases, sauces, préparations labo, rendements par lot et coûts imbriqués.",
    status: "Modèle de données prêt",
    icon: Archive,
  },
  {
    href: "/costs",
    title: "Coûts matières",
    description: "Calculs automatiques depuis achats, fiches, pertes et inventaires.",
    status: "À implémenter",
    icon: BadgeEuro,
  },
  {
    href: "/margins",
    title: "Marges",
    description: "Pilotage marge brute, marge nette estimée, mix produit et dérives.",
    status: "Tableau de bord initial",
    icon: BarChart3,
  },
  {
    href: "/allergens",
    title: "Allergènes",
    description: "Matrice allergènes ingrédients, recettes, étiquettes et exports salle.",
    status: "Champ stock prêt",
    icon: AlertTriangle,
  },
  {
    href: "/haccp",
    title: "HACCP / PMS",
    description: "Plan de maîtrise sanitaire, contrôles, preuves, actions correctives.",
    status: "API températures prête",
    icon: ShieldCheck,
  },
  {
    href: "/temperatures",
    title: "Relevés températures",
    description: "Saisie mobile, conformité, alertes froid/chaud et historique exportable.",
    status: "API CRUD initiale",
    icon: Activity,
  },
  {
    href: "/labels",
    title: "Étiquettes",
    description: "DLC, lots, allergènes, QR codes et impression cuisine.",
    status: "À implémenter",
    icon: Tags,
  },
  {
    href: "/production",
    title: "Production labo",
    description: "Ordres de production, besoins, lots, rendements et traçabilité.",
    status: "Navigation prête",
    icon: PackageCheck,
  },
  {
    href: "/planning",
    title: "Planning employés",
    description: "Équipe, postes, absences, coût main d'oeuvre et publication mobile.",
    status: "Module actif",
    icon: CalendarDays,
  },
  {
    href: "/time-clock",
    title: "Badgeuse employés",
    description: "Pointage, pauses, validation manager et export paie.",
    status: "Module actif",
    icon: Clock3,
  },
  {
    href: "/analytics",
    title: "Analyses",
    description: "Ventes, achats, pertes, productivité, food cost et prévisions.",
    status: "Tableau de bord initial",
    icon: BarChart3,
  },
  {
    href: "/orders",
    title: "Commandes fournisseurs",
    description: "Suggestions, bons de commande, statuts, réception et écarts facture.",
    status: "Navigation prête",
    icon: ReceiptText,
  },
  {
    href: "/ladition",
    title: "Synchronisation caisse L'Addition",
    description: "Configuration, statut et préparation des ventes depuis Paramètres > Intégrations.",
    status: "Section intégrations prête",
    icon: FileSpreadsheet,
  },
  {
    href: "/api-console",
    title: "API REST complète",
    description: "Documentation, tokens, webhooks, journaux API et intégration partenaires.",
    status: "FastAPI OpenAPI actif",
    icon: Code2,
  },
  {
    href: "/notifications",
    title: "Notifications temps réel",
    description: "WebSocket, alertes stock, HACCP, imports OCR et actions manager.",
    status: "WebSocket initial",
    icon: Bell,
  },
  {
    href: "/uploads",
    title: "Import glisser-déposer",
    description: "Dépôt factures, photos, pièces jointes et analyse asynchrone.",
    status: "Endpoint facture prêt",
    icon: UploadCloud,
  },
  {
    href: "/reports",
    title: "PDF et Excel",
    description: "Exports compta, inventaire, HACCP, étiquettes, fiches techniques.",
    status: "À implémenter",
    icon: FileDown,
  },
  {
    href: "/history",
    title: "Historique complet",
    description: "Timeline achats, stocks, recettes, employés, imports et validations.",
    status: "Modèle audit prêt",
    icon: History,
  },
  {
    href: "/audit",
    title: "Audit logs",
    description: "Journal inviolable des actions critiques, rôles et changements.",
    status: "API écriture partielle",
    icon: FileArchive,
  },
  {
    href: "/settings",
    title: "Paramètres entreprise",
    description: "Société, restaurants, utilisateurs, rôles, sécurité et intégrations.",
    status: "Modèle de données prêt",
    icon: Settings,
  },
  {
    href: "/team",
    title: "Multi-utilisateurs",
    description: "Invitations, rôles, permissions par restaurant et audit d'accès.",
    status: "Module actif",
    icon: Users,
  },
  {
    href: "/print",
    title: "Impression cuisine",
    description: "Étiquettes, fiches, ordres de production et exports opérationnels.",
    status: "À implémenter",
    icon: Printer,
  },
];

export type ModuleDefinition = (typeof modules)[number];

export function getModuleByHref(href: string) {
  return modules.find((module) => module.href === href);
}
